language: c

sudo: true
osx_image: xcode8
os:
  # Ubuntu Trusty 14.04 (GCE)
  - linux
  # Mac OS X 10.11
  - osx

env:
  - DEFINITION=5.2.17
  - DEFINITION=5.3.29
  - DEFINITION=5.4.45
  - DEFINITION=5.5.38
  - DEFINITION=5.6.31
  - DEFINITION=7.0.22
  - DEFINITION=7.1.8
  - DEFINITION=7.2.0beta2

# See here for osx_image: https://docs.travis-ci.com/user/reference/osx/#OS-X-Version
matrix:
  include:
    # macOS 10.12 + PHP 5.6
    - os: osx
      osx_image: xcode8.3
      env:
        - DEFINITION=5.6.31
    # macOS 10.12 + PHP 7.1
    - os: osx
      osx_image: xcode8.3
      env:
        - DEFINITION=7.1.8

addons:
  apt:
    packages:
      - libmcrypt-dev
      - libtidy-dev
      - libicu-dev
      - php5-cli
      - re2c

cache:
  ccache: true

before_install:
  - export PHP_BUILD_EXTRA_MAKE_ARGUMENTS="-j2"
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" &&
          "$DEFINITION" =~ ^("5.2.".*|"5.3."[0-6])$ ]]; then
        export PHP_BUILD_CONFIGURE_OPTS="--with-libdir=lib/x86_64-linux-gnu"
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        if [[ "$DEFINITION" =~ ^("5."[23]|"5.4."([0-9]|1[0-4])$) ]]; then
            export LIBS="-lssl -lcrypto"
        fi
        brew update
        brew install ccache re2c libmcrypt icu4c
        brew outdated openssl || brew upgrade openssl
        brew outdated libxml2 || brew upgrade libxml2
        if [[ "$DEFINITION" == "5.2.17" ]]; then
            brew install mysql
        fi
        export PATH="/usr/local/opt/ccache/libexec:$PATH"
    fi
  - ccache --version
  - ccache --zero-stats

install:
  - git clone https://github.com/sstephenson/bats
  - bats/install.sh $HOME
  - export PATH=$HOME/bin:$HOME/libexec:$PATH
  - bats --version

script:
  - ./run-tests.sh $DEFINITION

after_failure:
  - tail -n 5000 cat $(ls -r /tmp/php-build*.log | head -n 1)

after_success:
    - ccache --show-stats
