sudo: false

addons:
 apt:
  packages:
   - php5-cli
   - git-core
   - libmcrypt-dev
   - libjpeg-dev
   - libreadline-dev
   - re2c
   - libtidy-dev

env:
  global:
    - PHPBUILD_EXTRA_MAKE_ARGUMENTS=-j2
  matrix:
    - DEFINITION=5.2.17 PHP_BUILD_CONFIGURE_OPTS="--with-libdir=lib/x86_64-linux-gnu"
    - DEFINITION=5.3.3 PHP_BUILD_CONFIGURE_OPTS="--with-libdir=lib/x86_64-linux-gnu"
    - DEFINITION=5.3.29
    - DEFINITION=5.4.45
    - DEFINITION=5.5.30
    - DEFINITION=5.6.15
    - DEFINITION=7.0.0RC6

script: ./run-tests.sh $DEFINITION

before_script:
    - git clone https://github.com/sstephenson/bats
    - bats/install.sh $HOME
    - export PATH=$HOME/bin:$HOME/libexec:$PATH
    - bats --version

after_failure:
    - cat $(ls -r /tmp/php-build*.log | head -n 1)
