sudo: false
osx_image: xcode8

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libmcrypt-dev
      - libtidy-dev
      - libicu-dev
      - php5-cli
      - re2c

env:
  global:
    - PHP_BUILD_EXTRA_MAKE_ARGUMENTS="-j2"
  matrix:
    - DEFINITION=7.2.0RC1

matrix:
  include:
    - os: osx
      osx_image: xcode9
      env: DEFINITION=7.2.0RC1
    - os: osx
      osx_image: xcode8.3
      env: DEFINITION=7.2.0RC1
    - os: osx
      osx_image: xcode8.2
      env: DEFINITION=7.2.0RC1
    - os: osx
      osx_image: xcode8.1
      env: DEFINITION=7.2.0RC1
    - os: osx
      osx_image: xcode7.3
      env: DEFINITION=7.2.0RC1
    - os: osx
      osx_image: xcode6.4
      env: DEFINITION=7.2.0RC1
    
before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" &&
          "$DEFINITION" =~ ^("5.2.".*|"5.3."[0-6])$ ]]; then
        export PHP_BUILD_CONFIGURE_OPTS="--with-libdir=lib/x86_64-linux-gnu"
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew info pkg-config
        pkg-config --debug --modversion libcurl
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        if [[ "$DEFINITION" =~ ^("5."[23]|"5.4."([0-9]|1[0-4])$) ]]; then
            export LIBS="-lssl -lcrypto"
        fi
        brew update
        brew install re2c libmcrypt openssl libxml2 icu4c
        if [[ "$DEFINITION" == "5.2.17" ]]; then
            brew install mysql
        fi
        if [[ "$DEFINITION" == "7.2.0RC1" ]]; then
            brew upgrade pkg-config
        fi
    fi

install:
  - git clone https://github.com/sstephenson/bats
  - bats/install.sh $HOME
  - export PATH=$HOME/bin:$HOME/libexec:$PATH
  - bats --version

script:
  - ./run-tests.sh $DEFINITION

after_failure:
  - cat $(ls -r /tmp/php-build*.log | head -n 1)
