sudo: false
osx_image: xcode8 # Mac OS X 10.11
language: c

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libmcrypt-dev
      - libtidy-dev
      - libicu-dev
      - php5-cli
      - re2c

env:
  global:
    - PHP_BUILD_EXTRA_MAKE_ARGUMENTS="-j2"
  matrix:
    - DEFINITION=5.2.17
    - DEFINITION=5.3.29
    - DEFINITION=5.4.45
    - DEFINITION=5.5.38
    - DEFINITION=5.6.31
    - DEFINITION=7.0.22
    - DEFINITION=7.1.8
    - DEFINITION=7.2.0beta2

matrix:
  include:
    # Linux + clang
    - os: linux
      compiler: clang
      env:
        - DEFINITION=5.6.31
        - DEFINITION=7.1.8
    # macOS 10.12
    - os: osx
      osx_image: xcode8.3
      env:
        - DEFINITION=5.6.31
        - DEFINITION=7.1.8

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" &&
          "$DEFINITION" =~ ^("5.2.".*|"5.3."[0-6])$ ]]; then
        export PHP_BUILD_CONFIGURE_OPTS="--with-libdir=lib/x86_64-linux-gnu"
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        if [[ "$DEFINITION" =~ ^("5."[23]|"5.4."([0-9]|1[0-4])$) ]]; then
            export LIBS="-lssl -lcrypto"
        fi
        brew update
        brew install re2c libmcrypt openssl libxml2 icu4c
        if [[ "$DEFINITION" == "5.2.17" ]]; then
            brew install mysql
        fi
    fi

install:
  - git clone https://github.com/sstephenson/bats
  - bats/install.sh $HOME
  - export PATH=$HOME/bin:$HOME/libexec:$PATH
  - bats --version

script:
  - ./run-tests.sh $DEFINITION

after_failure:
  - cat $(ls -r /tmp/php-build*.log | head -n 1)
