sudo: false
osx_image: xcode8

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libmcrypt-dev
      - libtidy-dev
      - libicu-dev
      - php5-cli
      - re2c

matrix:
  include:
    - os: osx
      osx_image: xcode9 # OSX 10.12
    - os: osx
      osx_image: xcode8.3 # OSX 10.12
    - os: osx
      osx_image: xcode8.2 # OSX 10.12
    - os: osx
      osx_image: xcode8.1 # OSX 10.12
    - os: osx
      osx_image: xcode8 # OSX 10.11
    - os: osx
      osx_image: xcode7.3 # OSX 10.11
    - os: osx
      osx_image: xcode6.4 # OSX 10.10


before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" &&
          "$DEFINITION" =~ ^("5.2.".*|"5.3."[0-6])$ ]]; then
        export PHP_BUILD_CONFIGURE_OPTS="--with-libdir=lib/x86_64-linux-gnu"
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        if [[ "$DEFINITION" =~ ^("5."[23]|"5.4."([0-9]|1[0-4])$) ]]; then
            export LIBS="-lssl -lcrypto"
        fi
        brew update
        brew install re2c libmcrypt openssl libxml2 icu4c
        if [[ "$DEFINITION" == "5.2.17" ]]; then
            brew install mysql
        fi
    fi

script:
  - curl --version
  - uname -a
