sudo: false

addons:
  apt:
    packages:
      - autoconf
      - automake
      - libmcrypt-dev
      - libtidy-dev
      - php5-cli
      - re2c

env:
  global:
    - PHPBUILD_EXTRA_MAKE_ARGUMENTS="-j2"
  matrix:
    - DEFINITION=5.2.17 PHP_BUILD_CONFIGURE_OPTS="--with-libdir=lib/x86_64-linux-gnu"
    - DEFINITION=5.3.3 PHP_BUILD_CONFIGURE_OPTS="--with-libdir=lib/x86_64-linux-gnu"
    - DEFINITION=5.3.29
    - DEFINITION=5.4.45
    - DEFINITION=5.5.30
    - DEFINITION=5.6.15
    - DEFINITION=7.0.0RC8

install:
  - git clone https://github.com/sstephenson/bats
  - bats/install.sh $HOME
  - export PATH=$HOME/bin:$HOME/libexec:$PATH
  - bats --version

script:
  - ./run-tests.sh $DEFINITION

after_failure:
  - cat $(ls -r /tmp/php-build*.log | head -n 1)
